-- =============================================================================
-- cfml-slack-chat : schema for PostgreSQL
-- Target: PostgreSQL 12 or later (identity columns, partial indexes)
--
-- Safe to run more than once. Every object is created only if it is absent, so
-- re-running this script against an existing database changes nothing.
--
-- psql -h localhost -U your_user -d your_database -f sql/postgresql.sql
--
-- An optional reset section is at the bottom. It is commented out, and it is
-- commented out for a reason.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- conversation
-- One row per customer conversation. slack_channel_id and slack_thread_ts are
-- null until Slack has accepted the opening message and told us where it went.
-- -----------------------------------------------------------------------------
create table if not exists conversation (
	conversation_id char(36) not null,
	visitor_name varchar(120) not null,
	visitor_email varchar(255) not null,
	status varchar(20) not null default 'waiting',
	access_token_hash char(64) not null,
	slack_channel_id varchar(32),
	slack_thread_ts varchar(32),
	created_at timestamp not null default (now() at time zone 'utc'),
	updated_at timestamp not null default (now() at time zone 'utc'),
	closed_at timestamp,
	constraint pk_conversation primary key (conversation_id),
	constraint ck_conversation_status check (status in ('active', 'waiting', 'closed'))
);

create index if not exists ix_conversation_status
	on conversation (status);

create index if not exists ix_conversation_updated
	on conversation (updated_at);

-- The pairing of channel and thread is how an inbound Slack reply finds its
-- conversation, so it has to be both unique and fast.
create unique index if not exists ux_conversation_slack_thread
	on conversation (slack_channel_id, slack_thread_ts)
	where slack_channel_id is not null and slack_thread_ts is not null;


-- -----------------------------------------------------------------------------
-- conversation_message
-- Customer and support messages share one ordered stream. message_id is the
-- cursor the browser's SSE connection reads from.
-- -----------------------------------------------------------------------------
create table if not exists conversation_message (
	message_id bigint generated by default as identity,
	conversation_id char(36) not null,
	sender_type varchar(16) not null,
	sender_id varchar(64),
	sender_name varchar(120),
	body text not null,
	source varchar(16) not null,
	slack_event_id varchar(64),
	slack_message_ts varchar(32),
	created_at timestamp not null default (now() at time zone 'utc'),
	constraint pk_conversation_message primary key (message_id),
	constraint fk_message_conversation foreign key (conversation_id)
		references conversation (conversation_id) on delete restrict,
	constraint ck_message_sender_type check (sender_type in ('customer', 'support', 'system')),
	constraint ck_message_source check (source in ('web', 'slack', 'system'))
);

create index if not exists ix_message_conversation
	on conversation_message (conversation_id, message_id);

-- Two independent guarantees that one Slack reply becomes one customer-visible
-- message, no matter how many times Slack delivers the event.
create unique index if not exists ux_message_slack_ts
	on conversation_message (conversation_id, slack_message_ts)
	where slack_message_ts is not null;

create unique index if not exists ux_message_slack_event
	on conversation_message (slack_event_id)
	where slack_event_id is not null;


-- -----------------------------------------------------------------------------
-- slack_event_inbox
-- Verified Slack event callbacks, written by the webhook and drained by the
-- processor. event_id is Slack's globally unique identifier and is the primary
-- key, which is what makes duplicate delivery a no-op rather than a bug.
-- -----------------------------------------------------------------------------
create table if not exists slack_event_inbox (
	event_id varchar(64) not null,
	event_type varchar(64) not null,
	inner_event_type varchar(64),
	payload text not null,
	raw_body text not null,
	retry_num integer not null default 0,
	retry_reason varchar(64),
	received_at timestamp not null default (now() at time zone 'utc'),
	processed_at timestamp,
	attempt_count integer not null default 0,
	last_error varchar(1000),
	status varchar(16) not null default 'pending',
	next_attempt_at timestamp not null default (now() at time zone 'utc'),
	claimed_by varchar(64),
	constraint pk_slack_event_inbox primary key (event_id),
	constraint ck_event_status check (status in ('pending', 'processing', 'processed', 'ignored', 'failed'))
);

create index if not exists ix_event_status
	on slack_event_inbox (status, next_attempt_at);

create index if not exists ix_event_received
	on slack_event_inbox (received_at);


-- -----------------------------------------------------------------------------
-- slack_outbound_delivery
-- The durable queue for customer messages on their way to Slack. One row per
-- message, so a Slack outage delays delivery instead of losing it.
-- -----------------------------------------------------------------------------
create table if not exists slack_outbound_delivery (
	delivery_id bigint generated by default as identity,
	conversation_id char(36) not null,
	message_id bigint not null,
	destination varchar(32) not null default 'slack',
	status varchar(16) not null default 'pending',
	attempt_count integer not null default 0,
	next_attempt_at timestamp not null default (now() at time zone 'utc'),
	last_attempt_at timestamp,
	last_error varchar(1000),
	slack_channel_id varchar(32),
	slack_thread_ts varchar(32),
	created_at timestamp not null default (now() at time zone 'utc'),
	completed_at timestamp,
	claimed_by varchar(64),
	constraint pk_slack_outbound_delivery primary key (delivery_id),
	constraint uq_delivery_message unique (message_id),
	constraint fk_delivery_conversation foreign key (conversation_id)
		references conversation (conversation_id) on delete restrict,
	constraint fk_delivery_message foreign key (message_id)
		references conversation_message (message_id) on delete restrict,
	constraint ck_delivery_status check (status in ('pending', 'processing', 'sent', 'failed', 'abandoned'))
);

create index if not exists ix_delivery_status
	on slack_outbound_delivery (status, next_attempt_at);

create index if not exists ix_delivery_conversation
	on slack_outbound_delivery (conversation_id, message_id);


-- =============================================================================
-- Optional reset. Uncomment only when you want the test data gone.
-- Deletion order matters: the foreign keys are restrict, deliberately, so that
-- deleting a conversation cannot quietly orphan its messages.
-- =============================================================================
-- drop table if exists slack_outbound_delivery;
-- drop table if exists slack_event_inbox;
-- drop table if exists conversation_message;
-- drop table if exists conversation;
